name: deploy iCalendar files

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.HEBESI_HE2BWEB }}

      - name: generate config file
        run: |
          # the redirection avoids progress meter
          git clone --depth 1 git@github.com:HEB-ESI/he2besi-web 2>&1 | cat
          mkdir -p build/config
          node scripts/generate-calendars-json.js ical/2022-2023/q2 he2besi-web/jekyllsrc/_data/personnels.json >build/calendars.json
          npm install
          node scripts/getEvents.mjs -d ical/2022-2023/q2/groupes/ >build/events.json
          node scripts/generate-ics.mjs ical/2022-2023/q2/ build/events.json
          { printf '<p>Last update: <time>%s</time></p>' "$(date)"; } >build/index.html
          mv ical -t build
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
